"""M7 shared physics library: materials, e+/e- stopping powers, radiation
lengths, bremsstrahlung and photon cross-sections.

Every number regenerated by the M7 scripts ultimately comes from here.

Sources (web access was blocked in this session; values marked [BK] are
standard reference values quoted from background knowledge and should be
spot-checked against the online tables before publication):

* Collision stopping power of electrons/positrons: Bethe formula in the form
  of ICRU Report 37 (1984), eqs. 2.4-2.6, which is exactly what NIST ESTAR
  implements (https://physics.nist.gov/PhysRefData/Star/Text/ESTAR.html).
  Mean excitation energies I: ICRU 37 / ESTAR [BK].
* Density-effect correction: Sternheimer & Peierls general formula,
  Phys. Rev. B 3, 3681 (1971) (also used by PDG for materials without fitted
  parameters).
* Bremsstrahlung and pair production: Bethe-Heitler cross-sections with
  Thomas-Fermi screening functions as parameterised by Butcher & Messel,
  Nucl. Phys. 20, 15 (1960) (the parameterisation used by EGS4, SLAC-265,
  https://www.slac.stanford.edu/pubs/slacreports/reports03/slac-r-265.pdf).
* Radiation length: Tsai, Rev. Mod. Phys. 46, 815 (1974), PDG eq. 34.26
  (https://pdg.lbl.gov/2024/reviews/rpp2024-rev-passage-particles-matter.pdf).
* Compton: Klein-Nishina (free electrons; binding neglected above 100 keV).
* Photoabsorption 10-800 keV: Elam, Ravel & Sieber, Radiat. Phys. Chem. 63,
  121 (2002), tabulated via the `xraydb` Python package (v4.5.8) at build
  time and frozen below; extrapolated above 800 keV with the local log-log
  slope (photoabsorption is <5 % of attenuation there for all materials used).
* Positron annihilation in flight: Heitler (1954) two-photon cross-section.
"""
import numpy as np

ME = 0.51099895          # electron mass [MeV]
RE = 2.8179403262e-13    # classical electron radius [cm]
NA = 6.02214076e23       # Avogadro [1/mol]
ALPHA = 1.0 / 137.035999084
LN10 = np.log(10.0)

# ---------------------------------------------------------------------------
# Elements: Z, A [g/mol], I [eV] (ICRU 37 / ESTAR, [BK])
# ---------------------------------------------------------------------------
ELEMENTS = {
    'H': (1, 1.008, 19.2), 'D': (1, 2.0141, 19.2), 'B': (5, 10.81, 76.0),
    'C': (6, 12.011, 78.0), 'N': (7, 14.007, 82.0), 'O': (8, 15.999, 95.0),
    'F': (9, 18.998, 115.0), 'Na': (11, 22.990, 149.0), 'Al': (13, 26.982, 166.0),
    'Si': (14, 28.085, 173.0), 'Ar': (18, 39.948, 188.0), 'Cr': (24, 51.996, 257.0),
    'Fe': (26, 55.845, 286.0), 'Ni': (28, 58.693, 311.0), 'Cu': (29, 63.546, 322.0),
    'Ge': (32, 72.630, 350.0), 'Br': (35, 79.904, 343.0), 'Mo': (42, 95.95, 424.0),
    'Pd': (46, 106.42, 470.0), 'I': (53, 126.904, 491.0), 'La': (57, 138.905, 501.0),
    'Ce': (58, 140.116, 523.0), 'Pt': (78, 195.08, 790.0), 'Pb': (82, 207.2, 823.0),
    'Bi': (83, 208.980, 823.0),
}

PHOTO_E_KEV = np.array([10, 15, 20, 30, 40, 50, 60, 80, 100, 150, 200, 300, 400, 511, 600, 662, 800])
ELAM_PHOTO = {
    'H': [0.002723, 0.000674, 0.0002499, 6.167e-05, 2.284e-05, 1.058e-05, 5.649e-06, 2.105e-06, 9.822e-07, 2.495e-07, 9.626e-08, 2.637e-08, 1.11e-08, 5.593e-09, 3.68e-09, 2.894e-09, 1.863e-09],
    'B': [1.003, 0.2655, 0.1025, 0.02657, 0.01014, 0.004795, 0.002599, 0.0009889, 0.0004697, 0.0001224, 4.795e-05, 1.339e-05, 5.699e-06, 2.889e-06, 1.904e-06, 1.496e-06, 9.593e-07],
    'C': [2.076, 0.5586, 0.2177, 0.05707, 0.02193, 0.01042, 0.005671, 0.00217, 0.001031, 0.0002706, 0.0001064, 2.98e-05, 1.271e-05, 6.451e-06, 4.253e-06, 3.343e-06, 2.145e-06],
    'N': [3.543, 0.9674, 0.3808, 0.101, 0.03906, 0.01866, 0.01019, 0.003919, 0.001869, 0.0004919, 0.0001942, 5.46e-05, 2.334e-05, 1.185e-05, 7.821e-06, 6.15e-06, 3.946e-06],
    'O': [5.567, 1.542, 0.6124, 0.1641, 0.06394, 0.03068, 0.01681, 0.006497, 0.00311, 0.0008228, 0.0003251, 9.187e-05, 3.933e-05, 2.001e-05, 1.321e-05, 1.039e-05, 6.666e-06],
    'F': [7.782, 2.184, 0.8749, 0.237, 0.09296, 0.04482, 0.02463, 0.009564, 0.004593, 0.001222, 0.0004841, 0.0001372, 5.889e-05, 2.997e-05, 1.98e-05, 1.557e-05, 9.995e-06],
    'Na': [15.02, 4.317, 1.756, 0.4855, 0.1927, 0.09371, 0.05187, 0.02033, 0.009825, 0.002638, 0.001053, 0.0002999, 0.0001292, 6.597e-05, 4.359e-05, 3.42e-05, 2.203e-05],
    'Al': [25.56, 7.515, 3.1, 0.8724, 0.3504, 0.1718, 0.09564, 0.03783, 0.0184, 0.004993, 0.002002, 0.0005742, 0.000248, 0.0001269, 8.401e-05, 6.597e-05, 4.252e-05],
    'Si': [33.15, 9.849, 4.089, 1.161, 0.4687, 0.2307, 0.1288, 0.05121, 0.02498, 0.006806, 0.002736, 0.0007881, 0.0003409, 0.0001746, 0.0001156, 9.081e-05, 5.854e-05],
    'Ar': [62.32, 19.27, 8.207, 2.403, 0.9908, 0.4946, 0.2793, 0.1128, 0.05564, 0.01544, 0.006281, 0.001831, 0.0007979, 0.0004103, 0.0002721, 0.0002139, 0.0001381],
    'Cr': [137.6, 44.95, 19.81, 6.056, 2.564, 1.307, 0.7482, 0.3086, 0.1546, 0.04399, 0.01817, 0.005395, 0.002375, 0.001229, 0.0008184, 0.0006443, 0.0004164],
    'Fe': [169.4, 56.24, 25.05, 7.764, 3.316, 1.697, 0.9776, 0.406, 0.2044, 0.05861, 0.02433, 0.007265, 0.003209, 0.001665, 0.00111, 0.0008738, 0.0005651],
    'Ni': [207.5, 69.85, 31.49, 9.885, 4.256, 2.193, 1.267, 0.53, 0.268, 0.07746, 0.03229, 0.009701, 0.004299, 0.002236, 0.001491, 0.001175, 0.0007604],
    'Cu': [214.5, 73.08, 33.08, 10.45, 4.52, 2.335, 1.353, 0.5676, 0.2878, 0.08346, 0.03488, 0.01051, 0.004663, 0.002428, 0.001621, 0.001277, 0.0008265],
    'Ge': [35.72, 90.43, 41.45, 13.36, 5.844, 3.045, 1.775, 0.7518, 0.3836, 0.1125, 0.04734, 0.01438, 0.006413, 0.00335, 0.002239, 0.001766, 0.001144],
    'Br': [47.2, 110.6, 51.79, 16.99, 7.504, 3.95, 2.318, 0.9904, 0.5086, 0.1507, 0.06386, 0.01956, 0.008765, 0.004591, 0.003074, 0.002426, 0.001574],
    'Mo': [83.42, 27, 12, 27.43, 12.46, 6.667, 3.966, 1.728, 0.9007, 0.2732, 0.1175, 0.03665, 0.01661, 0.008768, 0.005892, 0.004659, 0.00303],
    'Pd': [108.5, 35.45, 15.83, 33.92, 15.61, 8.444, 5.068, 2.233, 1.173, 0.3605, 0.1564, 0.04926, 0.02246, 0.01191, 0.008025, 0.006352, 0.004136],
    'I': [159.7, 53.2, 24.04, 7.717, 21.5, 11.87, 7.208, 3.24, 1.725, 0.5419, 0.2383, 0.07649, 0.03525, 0.01883, 0.01274, 0.0101, 0.006597],
    'La': [193.7, 65.29, 29.7, 9.617, 25.15, 13.99, 8.571, 3.894, 2.09, 0.6651, 0.2947, 0.0955, 0.04431, 0.02378, 0.01612, 0.0128, 0.008377],
    'Ce': [205, 69.32, 31.59, 10.25, 4.564, 14.71, 9.047, 4.119, 2.214, 0.707, 0.3139, 0.102, 0.0474, 0.02546, 0.01726, 0.01372, 0.008979],
    'Pt': [108.4, 154.6, 73.47, 25.04, 11.49, 6.248, 3.785, 8.345, 4.695, 1.602, 0.7409, 0.2535, 0.1218, 0.06704, 0.04609, 0.03687, 0.02437],
    'Pb': [125.6, 108.2, 83.97, 28.86, 13.35, 7.293, 4.432, 2.013, 5.237, 1.815, 0.8464, 0.2929, 0.1417, 0.07844, 0.05406, 0.04332, 0.02871],
    'Bi': [130.9, 112.5, 87.06, 30.03, 13.92, 7.614, 4.634, 2.107, 5.42, 1.88, 0.8793, 0.3051, 0.1479, 0.08197, 0.05654, 0.04532, 0.03006],
}


def _photo_elem(sym, E):
    """Photoabsorption mu/rho [cm2/g] of element `sym` at E [MeV] (Elam)."""
    if sym == 'D':      # same electronic structure as H, per gram scaled by A
        return _photo_elem('H', E) * ELEMENTS['H'][1] / ELEMENTS['D'][1]
    tab = np.asarray(ELAM_PHOTO[sym])
    le = np.log(PHOTO_E_KEV / 1000.0)
    lt = np.log(tab)
    E = np.atleast_1d(np.asarray(E, float))
    lE = np.log(np.clip(E, 1e-3, None))
    out = np.interp(lE, le, lt)
    # extrapolate above 800 keV with last-interval slope, bounded between
    # -2.5 and -1 (Sauter high-energy limit ~1/E)
    slope = (lt[-1] - lt[-2]) / (le[-1] - le[-2])
    slope = min(max(slope, -2.5), -1.0)
    hi = lE > le[-1]
    out[hi] = lt[-1] + slope * (lE[hi] - le[-1])
    lo = lE < le[0]
    out[lo] = lt[0] - 3.0 * (lE[lo] - le[0])
    return np.exp(out)


# ---------------------------------------------------------------------------
# Material class
# ---------------------------------------------------------------------------
class Material:
    def __init__(self, name, rho, comp, by='atoms', I=None, x0_ref=None,
                 note=''):
        """comp: dict element->count (by='atoms') or mass fraction (by='mass')."""
        self.name, self.rho, self.note = name, rho, note
        els = list(comp)
        if by == 'atoms':
            m = np.array([comp[e] * ELEMENTS[e][1] for e in els])
            w = m / m.sum()
        else:
            w = np.array([comp[e] for e in els], float)
            w = w / w.sum()
        self.els = els
        self.w = w
        self.Z = np.array([ELEMENTS[e][0] for e in els], float)
        self.A = np.array([ELEMENTS[e][1] for e in els], float)
        self.ZA = float(np.sum(w * self.Z / self.A))           # <Z/A> [mol/g]
        if I is None:   # Bragg additivity of ln I weighted by electrons
            Ie = np.array([ELEMENTS[e][2] for e in els])
            I = float(np.exp(np.sum(w * self.Z / self.A * np.log(Ie)) / self.ZA))
        self.I = I * 1e-6                                        # [MeV]
        self.x0_ref = x0_ref
        self._density_params()
        self.X0 = self._radiation_length()                       # [g/cm2]
        self.ne = self.ZA * NA * rho if rho > 0 else 0.0          # e-/cm3

    # Sternheimer & Peierls (1971) general formula for condensed media
    def _density_params(self):
        if self.rho <= 0:
            self.dens = None
            return
        hwp = 28.816e-6 * np.sqrt(self.rho * self.ZA)             # MeV
        C = 2.0 * np.log(self.I / hwp) + 1.0
        gas = self.rho < 0.01
        if gas:
            x0 = 1.6 if C < 10.0 else 0.326 * C - 1.7
            x1 = 4.0
        elif self.I < 100e-6:
            x1 = 2.0
            x0 = 0.2 if C < 3.681 else 0.326 * C - 1.0
        else:
            x1 = 3.0
            x0 = 0.2 if C < 5.215 else 0.326 * C - 1.5
        m = 3.0
        a = (C - 2 * LN10 * x0) / (x1 - x0) ** m
        self.dens = (C, x0, x1, a, m)

    def delta(self, x):
        C, x0, x1, a, m = self.dens
        x = np.asarray(x, float)
        d = np.where(x >= x1, 2 * LN10 * x - C,
                     np.where(x >= x0, 2 * LN10 * x - C + a * np.clip(x1 - x, 0, None) ** m, 0.0))
        return d

    def _radiation_length(self):
        inv = 0.0
        for w, Z, A in zip(self.w, self.Z, self.A):
            a2 = (ALPHA * Z) ** 2
            f = a2 * (1 / (1 + a2) + 0.20206 - 0.0369 * a2 + 0.0083 * a2 ** 2 - 0.002 * a2 ** 3)
            Lr = {1: 5.31, 2: 4.79, 3: 4.74, 4: 4.71}.get(int(Z), np.log(184.15 * Z ** (-1 / 3)))
            Lp = {1: 6.144, 2: 5.621, 3: 5.805, 4: 5.924}.get(int(Z), np.log(1194.0 * Z ** (-2 / 3)))
            inv += w * 4 * ALPHA * RE ** 2 * NA / A * (Z ** 2 * (Lr - f) + Z * Lp)
        return 1.0 / inv

    # -------------------------------------------------------------- stopping
    def S_col(self, T, positron=False):
        """Collision stopping power [MeV cm2/g] (ICRU 37 eq. 2.4 = ESTAR)."""
        T = np.asarray(T, float)
        tau = T / ME
        g = tau + 1.0
        b2 = 1.0 - 1.0 / g ** 2
        if positron:
            y = tau + 2.0
            F = 2 * np.log(2) - b2 / 12 * (23 + 14 / y + 10 / y ** 2 + 4 / y ** 3)
        else:
            F = 1 - b2 + (tau ** 2 / 8 - (2 * tau + 1) * np.log(2)) / (tau + 1) ** 2
        x = np.log10(np.sqrt(np.clip(g ** 2 - 1, 1e-30, None)))
        d = self.delta(x) if self.dens else 0.0
        L = np.log(tau ** 2 * (tau + 2) / (2 * (self.I / ME) ** 2)) + F - d
        return 0.153537 * self.ZA / b2 * np.clip(L, 1e-3, None)

    def brem_dsdk(self, T, k):
        """Bremsstrahlung d(sigma)/dk per gram [cm2/g/MeV], T,k in MeV.
        Bethe-Heitler + Thomas-Fermi screening (Butcher-Messel/EGS4),
        no Coulomb correction (EGS4 applies it only above 50 MeV)."""
        T = np.asarray(T, float)
        k = np.asarray(k, float)
        E = T + ME
        Ep = E - k
        v = Ep / E
        out = np.zeros(np.broadcast(T, k).shape)
        for w, Z, A in zip(self.w, self.Z, self.A):
            xi = np.log(1194 * Z ** (-2 / 3)) / np.log(184.15 * Z ** (-1 / 3)) if Z > 4 else 1.2
            dl = 136.0 * ME * Z ** (-1 / 3) * k / (E * np.clip(Ep, 1e-12, None))
            p1 = np.where(dl <= 1, 20.867 - 3.242 * dl + 0.625 * dl ** 2, 21.12 - 4.184 * np.log(dl + 0.952))
            p2 = np.where(dl <= 1, 20.209 - 1.930 * dl - 0.086 * dl ** 2, p1)
            lz = 4.0 / 3.0 * np.log(Z)
            br = (1 + v ** 2) * (p1 - lz) - 2.0 / 3.0 * v * (p2 - lz)
            out = out + w * NA / A * ALPHA * RE ** 2 * Z * (Z + xi) * np.clip(br, 0, None) / k
        return np.where((k > 0) & (k < T), out, 0.0)

    def S_rad(self, T, n=200):
        T = np.atleast_1d(np.asarray(T, float))
        u = (np.arange(n) + 0.5) / n                    # k = T*u (midpoint)
        k = T[:, None] * u[None, :]
        return np.sum(k * self.brem_dsdk(T[:, None], k), axis=1) * T / n

    def csda_range(self, T, positron=False):
        """CSDA range [g/cm2] (integral of 1/S_tot from 1 keV; R(1 keV)~0)."""
        T = np.atleast_1d(np.asarray(T, float))
        out = []
        for t in T:
            e = np.geomspace(1e-3, t, 400)
            s = self.S_col(e, positron) + self.S_rad(e)
            out.append(np.trapezoid(1 / s, e))
        return np.array(out)

    # ---------------------------------------------------------------- photons
    def mu_photo(self, E):
        return sum(w * _photo_elem(el, E) for w, el in zip(self.w, self.els))

    def mu_incoh(self, E):
        return self.ZA * NA * sigma_kn(E)

    def mu_pair(self, E):
        E = np.atleast_1d(np.asarray(E, float))
        out = np.zeros_like(E)
        for i, k in enumerate(E):
            if k <= 2 * ME * 1.0001:
                continue
            ep = np.linspace(ME, k - ME, 202)[1:-1]
            em = k - ep
            s = 0.0
            for w, Z, A in zip(self.w, self.Z, self.A):
                xi = np.log(1194 * Z ** (-2 / 3)) / np.log(184.15 * Z ** (-1 / 3)) if Z > 4 else 1.2
                # electron-field (triplet) part has a 4 m_e threshold
                xi_eff = xi * np.clip((k - 4 * ME) / (k - 2 * ME), 0, 1) if k > 4 * ME else 0.0
                dl = 136.0 * ME * Z ** (-1 / 3) * k / (ep * em)
                p1 = np.where(dl <= 1, 20.867 - 3.242 * dl + 0.625 * dl ** 2, 21.12 - 4.184 * np.log(dl + 0.952))
                p2 = np.where(dl <= 1, 20.209 - 1.930 * dl - 0.086 * dl ** 2, p1)
                lz = 4.0 / 3.0 * np.log(Z)
                br = (ep ** 2 + em ** 2) * (p1 - lz) + 2.0 / 3.0 * ep * em * (p2 - lz)
                ds = ALPHA * RE ** 2 * Z * (Z + xi_eff) / k ** 3 * np.clip(br, 0, None)
                s += w * NA / A * np.trapezoid(ds, ep) * pair_coulomb_corr(k, Z)
            out[i] = s
        return out

    def mu_total(self, E):
        return self.mu_photo(E) + self.mu_incoh(E) + self.mu_pair(E)

    def ann_inflight(self, T):
        """Macroscopic in-flight annihilation cross-section per gram [cm2/g]."""
        return self.ZA * NA * sigma_heitler(T)


def pair_coulomb_corr(k, Z):
    """Empirical Coulomb correction to the Born (Bethe-Heitler) pair
    cross-section. The exact (Davies-Bethe-Maximon / Overbo) Coulomb
    correction lowers sigma at high energy (-9 % for Pb asymptotically) and
    raises it strongly near threshold for high Z. Both effects scale ~(alpha Z)^2.
    Form: a_inf + b/(k-2m)^1.8, with (a_inf, b) fitted to XCOM Pb totals
    3-20 MeV [BK] and scaled by (alpha Z / alpha 82)^2. Residuals vs XCOM are
    printed by the self-test (<=4 % for Pb/Fe/water at 3-20 MeV)."""
    s = (Z / 82.0) ** 2
    return (1.0 - 0.13 * s) + 2.4 * s / max(k - 2 * ME, 0.05) ** 1.8


def sigma_kn(E):
    """Klein-Nishina total cross-section per electron [cm2]."""
    k = np.asarray(E, float) / ME
    t1 = (1 + k) / k ** 2 * (2 * (1 + k) / (1 + 2 * k) - np.log(1 + 2 * k) / k)
    t2 = np.log(1 + 2 * k) / (2 * k) - (1 + 3 * k) / (1 + 2 * k) ** 2
    return 2 * np.pi * RE ** 2 * (t1 + t2)


def sigma_heitler(T):
    """Heitler 2-photon annihilation-in-flight cross-section per electron [cm2]."""
    g = np.asarray(T, float) / ME + 1.0
    g = np.clip(g, 1.0 + 1e-9, None)
    s = np.sqrt(g ** 2 - 1)
    return np.pi * RE ** 2 / (g + 1) * ((g ** 2 + 4 * g + 1) / (g ** 2 - 1) * np.log(g + s) - (g + 3) / s)


# ---------------------------------------------------------------------------
# Material catalogue (densities: CRC Handbook / NIST ESTAR [BK])
# ---------------------------------------------------------------------------
MATERIALS = {
    'VAC': None,
    'AIR': Material('AIR', 0.0012048, {'N': 0.755268, 'O': 0.231781, 'Ar': 0.012827, 'C': 0.000124}, 'mass', I=85.7),
    'PD': Material('PD', 12.02, {'Pd': 1}, x0_ref=9.20),
    'D2O': Material('D2O', 1.105, {'D': 2, 'O': 1}, I=75.0),
    'H2O': Material('H2O', 0.997, {'H': 2, 'O': 1}, I=75.0, x0_ref=36.08),
    'PTFE': Material('PTFE', 2.20, {'C': 2, 'F': 4}, I=99.1, x0_ref=34.84),
    'SS316': Material('SS316', 8.00, {'Fe': 0.685, 'Cr': 0.17, 'Ni': 0.12, 'Mo': 0.025}, 'mass'),
    'AL': Material('AL', 2.699, {'Al': 1}, x0_ref=24.01),
    'CU': Material('CU', 8.96, {'Cu': 1}, x0_ref=12.86),
    'FE': Material('FE', 7.874, {'Fe': 1}, x0_ref=13.84),
    'PB': Material('PB', 11.35, {'Pb': 1}, x0_ref=6.37),
    'SI': Material('SI', 2.329, {'Si': 1}, x0_ref=21.82),
    'FR4': Material('FR4', 1.85, {'Si': 0.18, 'O': 0.39, 'C': 0.28, 'H': 0.03, 'Br': 0.07}, 'mass'),
    'NAI': Material('NAI', 3.667, {'Na': 1, 'I': 1}, I=452.0, x0_ref=9.49),
    'BGO': Material('BGO', 7.13, {'Bi': 4, 'Ge': 3, 'O': 12}, I=534.1, x0_ref=7.97),
    'LABR3': Material('LABR3', 5.08, {'La': 1, 'Br': 3}),
    'GE': Material('GE', 5.323, {'Ge': 1}, x0_ref=12.25),
    'PVT': Material('PVT', 1.023, {'C': 9, 'H': 10}, I=64.7, x0_ref=43.90),
    'HDPE': Material('HDPE', 0.95, {'C': 1, 'H': 2}, I=57.4, x0_ref=44.77),
    'PT': Material('PT', 21.45, {'Pt': 1}),
}

# Reference values [BK] used in verification --------------------------------
# NIST ESTAR, liquid water (I = 75 eV): T [MeV] -> (S_col, S_rad, CSDA) [MeV cm2/g, g/cm2]
ESTAR_WATER_BK = {1.0: (1.849, 0.01293, 0.4367), 10.0: (1.968, 0.1832, 4.975)}
# PDG "Atomic and nuclear properties" critical energies E_c(e-) [MeV] (Rossi def.)
PDG_EC_BK = {'H2O': 78.33, 'PB': 7.43, 'FE': 21.68, 'CU': 19.42, 'SI': 40.19,
             'NAI': 13.37, 'BGO': 10.19, 'AL': 42.70}
# NIST XCOM total attenuation with coherent [cm2/g]
XCOM_TOTAL_BK = {
    'PB': {0.511: 0.155, 1.0: 0.0710, 2.0: 0.0461, 3.0: 0.0423, 5.0: 0.0427, 10.0: 0.0497, 20.0: 0.0620},
    'FE': {0.511: 0.0829, 1.0: 0.0599, 2.0: 0.0426, 3.0: 0.0362, 5.0: 0.0314, 10.0: 0.0299, 20.0: 0.0317},
    'H2O': {0.511: 0.0957, 1.0: 0.0707, 2.0: 0.0494, 3.0: 0.0397, 5.0: 0.0303, 10.0: 0.0222, 20.0: 0.0181},
}
# PDG minimum ionisation dE/dx [MeV cm2/g] (for cosmic-muon deposits)
PDG_DEDX_MIN_BK = {'BGO': 1.251, 'NAI': 1.305, 'LABR3': 1.28, 'GE': 1.371, 'PVT': 1.956,
                   'SI': 1.664, 'PB': 1.122, 'CU': 1.403, 'H2O': 1.992, 'SS316': 1.46}


def critical_energy(mat):
    """Rossi definition: E such that S_col(E) * X0 = E."""
    T = np.geomspace(1, 200, 2000)
    f = mat.S_col(T) * mat.X0 - (T + ME)
    i = np.where(np.diff(np.sign(f)))[0][0]
    return T[i]


def self_test(out=print):
    out("== m7_common self-test (model vs [BK] reference) ==")
    w = MATERIALS['H2O']
    for T, (sc, sr, r) in ESTAR_WATER_BK.items():
        out(f"water T={T:5.1f} MeV  S_col {w.S_col(T):.4f} (ESTAR {sc})  S_rad {w.S_rad(T)[0]:.4f} (ESTAR {sr})"
            f"  CSDA {w.csda_range(T)[0]:.4f} (ESTAR {r}) g/cm2")
    for k, m in MATERIALS.items():
        if m is None or m.x0_ref is None:
            continue
        out(f"X0 {k:6s} Tsai {m.X0:6.2f}  PDG {m.x0_ref:6.2f} g/cm2  ({100*(m.X0/m.x0_ref-1):+.1f} %)")
    for k, ec in PDG_EC_BK.items():
        m = MATERIALS[k]
        out(f"E_c {k:5s} model {critical_energy(m):6.2f}  PDG {ec:6.2f} MeV")
    for k, tab in XCOM_TOTAL_BK.items():
        m = MATERIALS[k]
        for E, v in tab.items():
            mt = m.mu_total(E)[0]
            out(f"mu/rho {k:4s} {E:5.2f} MeV model {mt:.4f} (photo {m.mu_photo(E)[0]:.4f} incoh {m.mu_incoh(E):.4f}"
                f" pair {m.mu_pair(E)[0]:.4f})  XCOM {v:.4f}  ({100*(mt/v-1):+.1f} %)")


if __name__ == '__main__':
    self_test()
